#ifndef AUDIOZIP_UTILS_HPP
#define AUDIOZIP_UTILS_HPP


#define SAMPLE_SIZE  4
#define CHANNEL 1
#define SAMPLE_RATE  48000
#define FRAMES_PER_BUFFER  3840
#define BITRATE  64000

// 최대 지연 시간 80 * 8 ms
#define MAX_DELAY_LIMIT_COUNT  8

#define ERROR_NO_DEFAULT_INPUT_DEVICE  -1
#define ERROR_OPEN_INPUT_DEVICE  -2
#define ERROR_START_INPUT_DEVICE  -3

#define ERROR_NO_DEFAULT_OUTPUT_DEVICE  -4
#define ERROR_OPEN_OUTPUT_DEVICE  -5
#define ERROR_START_OUTPUT_DEVICE  -6

#define ERROR_OPEN_ENCODER  -7

#define ERROR_OPEN_DECODE  -8

#endif  // AUDIOZIP_UTILS_HPP